src/client.ts
src/index.ts
src/unleash.ts
test/client.test.js
test/unleash.test.js

add fallbackValue stupport to isEnabled

---

package.json
src/repository.ts
src/unleash.ts

- Added explicit null checking a few places where neccessary
- Removed some null checks in places where the compiler should tells us about nullability

- Enabled the strictNullChecks flag when compiling

---

src/repository.ts
test/repository.test.js

k8s for instance is just `unleash-server`

Remove silly url check

---

examples/with_instance.ts
src/client.ts
src/unleash.ts
test/client.test.js
test/global.test.js
test/unleash.test.js

* having a custom errorHandler was not intended
cc @ivarconr

remove errorHandler, use error event instead

---

src/client.ts

Closes #28
cc @SimenB @ivarconr

emit warning once on missing strategy

---

README.md
examples/custom_strategy.js
examples/simple_usage.js
examples/with_context.js
package.json
src/context.ts
src/strategy.ts
src/strategy/application-hostname-strategy.ts
src/strategy/default-strategy.ts
src/strategy/gradual-rollout-random.ts
src/strategy/gradual-rollout-session-id.ts
src/strategy/gradual-rollout-user-id.ts
src/strategy/index.ts
src/strategy/remote-addresss-strategy.ts
src/strategy/strategy.ts
src/strategy/user-with-id-strategy.ts
src/strategy/util.ts
src/unleash.ts
test/strategy/application-hostname-strategy.test.js
test/strategy/default-strategy.test.js
test/strategy/gradual-rollout-random.test.js
test/strategy/gradual-rollout-session-id.test.js
test/strategy/gradual-rollout-user-id.test.1.js
test/strategy/gradual-rollout-user-id.test.js
test/strategy/remote-address-strategy.test.js
test/strategy/user-with-id-strategy.test.js

Started on the node companion of standardizing unleash strategies:
see java changes here:
https://github.com/Unleash/unleash-client-java/pull/33
TODO:

Add unleash_context

---

test/metrics.test.js

test metrics happy path

---

package.json
src/strategy/util.ts
test/strategy/util.test.js

Java client PR https://github.com/Unleash/unleash-client-java/pull/45

Implement hashing with murmur

---

CHANGELOG.md
package.json
src/metrics.ts
yarn.lock

Add sdkVersion in client-register call

---

src/index.ts
src/unleash.ts
test/index.test.js
test/unleash.test.js
yarn.lock

This PR adds two methods to the client, needed for implementing an experimental multi variant strategy API.

Multi variant extensions

---

package.json
test/integration/client-specification.test.js
yarn.lock

WIP: Implement test runner for "Client specifications"

---

.codeclimate.yml
.travis.yml
CHANGELOG.md
README.md
jsconfig.json
package.json
src/client.ts
src/data-formatter.ts
src/index.ts
src/metrics.ts
src/repository.ts
src/request.ts
src/storage.ts
src/strategy/util.ts
src/unleash.ts
test/client.test.js
test/fixtures/format-0.json
test/fixtures/format-1.json
test/index.test.js
test/strategy/gradual-rollout-random.test.js
test/strategy/gradual-rollout-session-id.test.js
test/strategy/gradual-rollout-user-id.test.js
test/strategy/remote-address-strategy.test.js
test/strategy/user-with-id-strategy.test.js
test/unleash.network.test.js
tsconfig.json
yarn.lock

Noticed greenkeeper complaining all over, so went for a bump

Upgrade deps

---

src/strategy/gradual-rollout-random.ts
test/strategy/gradual-rollout-random.test.js

This is a follow up of https://github.com/Unleash/unleash-client-node/pull/132#discussion_r292938714.
Side note: do you see any advantage to exit early if percentage is 0?

chore: control gradual rollout strategy randomness

---

examples/with_constraints.js
package.json
src/client.ts
src/strategy/flexible-rollout-strategy.ts
src/strategy/index.ts
src/strategy/strategy.ts
test/integration/constraint.test.js
test/strategy/flexible-rollout-test.js
test/strategy/strategy-test.js
yarn.lock

This is an initial implementation of context support. Currently it is guarded behind the "flexibleRollout" strategy. General support for constraints for all strategies will be introduced in v. 4.x.

feat: add constraint support

---

src/unleash.ts
yarn.lock

Added static context interface to keep the convention and make the code more legible

chore: Added interface to static context

---

src/unleash.ts

As discussed in #199
fixes: #199

Use nextTick to emit ready event for client.

---

src/variant.ts
test/unleash.test.js
test/variants.test.js

Same as https://github.com/Unleash/unleash-client-node/pull/201 but for variants

feat: variant stickiness

---

CHANGELOG.md
src/unleash.ts
test/unleash.test.js

fix: Use sanitized url for metrics

---

README.md

This PR contains a few very minor tweaks to the wording of the new bootstrap sections in the readme.

docs: minor tweaks to the new bootstrap docs in the readme.

---

README.md

The changes were approved by the author of the PR, but the PR was
merged before they went in. This cleans that up.

docs: Add remaining change requests from #318

---

README.md

docs: fix example usage in readme

---

package.json
src/repository/index.ts
yarn.lock

If the SDK gets a socket hang up we will not get
a built in retry from make-fetch happen.
This fix will issue a new fetch in refreshInterval / 2 in order to handle this with a graceful feedback.

fix: handle socket hang up gracefully.

---

src/metrics.ts
src/url-utils.ts
test/metrics.network.test.js
test/metrics.test.js
test/unleash.network.test.js

feat: gracefully handle unsuccessful metrics post

---

.github/workflows/master.yaml
.github/workflows/prs.yaml
.github/workflows/release.yml
test/repository.test.js

Node 18 is the current LTS and Node 19 is the current version. Verifying compatibility seems reasonable
Closes #

chore: run CI on node versions 18 and 19

---

test/fake_repo.js
test/metrics.test.js
test/unleash.test.js

* unit test showing metrics reporting in isolation
* component test showing metrics reporting in the whole SDK app

test: metrics reporting

---

package.json
src/details.json

chore: release 3.21.0

---

.github/workflows/build-and-test.yaml

Send report to Coveralls only for one Node version

Fix CI test coverage reporting

---

examples/instrumented.js
src/metrics.ts

hackaheart: update metrics format

---

package.json
src/details.json

We were reporting beta version

fix: non beta version reporting

---

src/client.ts

Reduced number of calls to parent dependency check.

refactor: one parent dependency check

---

package.json
src/strategy/strategy.ts
src/variant.ts
yarn.lock

If variant doesn't have stickiness fall back to strategy stickiness.
Fixes updated and failing spec: https://github.com/Unleash/client-specification/pull/83

fix: variant stickiness from strategy

---

package.json
yarn.lock

Upgrading to the latest version of make-fetch-happen that doesn't break node 16 support (https://github.com/npm/make-fetch-happen/releases).
I wanted to merge https://github.com/Unleash/unleash-client-node/pull/582 but then I realized it drops node 16 support which we currently do support.

chore: upgrade make-fetch-happen

---

package.json
yarn.lock

Fixes https://github.com/Unleash/unleash-client-node/security/dependabot/23

fix: add ip to resolutions

---

README.md

Since we're only supporting Node.js 16 or newer, I think ESM makes sense. But happy to wait a bit too

Updated README to use ESM

---

src/repository/index.ts

After my fix in #616 the same error was return from http 429 & 404, added specific error for http 404

Fix wrong error when receiving 404 after #616

---

package.json
src/strategy/remote-addresss-strategy.ts
yarn.lock

Replacing `ip` pacakage for `ip-address` package to address https://nvd.nist.gov/vuln/detail/CVE-2024-29415.
Closes #620

feat: replacing ip package for ip-address package

---

README.md
src/helpers.ts
src/unleash-config.ts
src/unleash.ts

This reverts commit a3f3326546929c655f52a1eaa7d053e4e282f1e1, and reapplies https://github.com/Unleash/unleash-client-node/pull/637

Reapply "feat: automatically generated instanceId (#637)" (#640)

---

src/unleash.ts

Add extra headers to the streaming connection similar how we do polling headers.

feat: streaming headers

---

src/unleash.ts
src/uuidv4.ts

UUID generation with crypto has better uniqueness guarantees, but Math.random() solution is good enough for our use case (which is not security critical) and works better across all platforms.
This PR will fix the NextJS SDK build issue.
We use UUID for estimated connection counting which is using imprecise HyperLogLog anyway.

fix: cross platform uuid

---

src/request.ts
src/test/metrics.test.ts
src/test/repository.test.ts
src/test/request.test.ts

We found that `unleash-client-lang:version` convention is used a lot so for the new header we can stick to it for now.

fix: use existing convention for sdk name

---

src/request.ts
src/test/metrics.test.ts
src/test/repository.test.ts
src/test/request.test.ts
src/test/unleash.test.ts

x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.

fix: drop x prefix

---

README.md

Updates the readme to add an overview of Unleash. Fixes minor typos

Update readme with Unleash description, fix minor typos

---

src/request.ts
src/test/repository.test.ts

Prevent overwriting unleash headers with custom headers.

fix: prevent unleash header overwrite

---

src/request.ts
src/test/repository.test.ts

fix: can overwrite sdk header

---

src/feature.ts
src/repository/index.ts
src/test/repository.test.ts

Parse delta response. We want to handle scenarios when delta response is invalid. Since we don't use any advanced parsing libraries I did simple check for now which should suffice for most scenarios.

feat: parse delta response

---

src/impact-metrics/environment-resolver.ts
src/impact-metrics/metric-client.ts
src/test/impact-metrics/environment-resolver.test.ts

Impact metrics should report environment from key not static context when possible

feat: impact metrics env resolver

---

src/impact-metrics/metric-client.ts
src/impact-metrics/metric-types.ts
src/test/impact-metrics/metric-client.test.ts
src/unleash.ts

Impact Metrics Flag Context
This PR adds support for including feature flag context in impact metrics. This enhancement allows users to track metrics with associated feature flag information, providing more detailed insights into how feature flags affect application metrics.
- Added `MetricFlagContext` interface to represent feature flag context in metrics
- Enhanced `MetricsAPI` to accept flag context when incrementing counters or updating gauges
- Implemented `getFlagLabels` method to extract flag-related labels from context (important: we don't count metrics or emit impression events)
- Changed `client` property in `Unleash` class from `private` to `protected` to allow access from subclasses
Users can now provide feature flag context when incrementing counters or updating gauges: …

feat: impact metric flag context
