Unleash/unleash-node-sdk

.travis.yml, examples/custom_strategy.js, package.json, src/repository.ts, src/unleash.ts, test/client.test.js, test/repository.test.js, test/storage.test.js, test/unleash.test.js
Without this change, it fails on install with:
```
> unleash-client@1.0.0-alpha.1 build /Users/simbekkh/repos/express-base/node_modules/unleash-client
> tsc src/*.ts -d --sourceMap --outdir ./lib --lib ES6,ES5
sh: tsc: command not found
```
If I install typescript, it still fails because the source code is not included in the package.
```
> unleash-client@1.0.0-alpha.1 build /Users/simbekkh/repos/express-base/node_modules/unleash-client
> tsc src/*.ts -d --sourceMap --outdir ./lib --lib ES6,ES5
error TS6053: File 'src/*.ts' not found.
```
Also allow this to be run on Node@7 without warnings (release imminent)
/cc @sveisvei @ivarconr
=> Fix install

package.json
It changed from deprecated node-uuid to uuid
=> Use minimum 2.79 of request

package.json, src/strategy/remote-addresss-strategy.ts, test/strategy/remote-address-strategy.test.js
Adding a gazilion IPs manually is somewhat of a pain, therefor adding support for IPv4 ranges would really make things easier. 
This PR uses the ip module to validate the ranges. I have not updated the docs on this as I wasn't sure if that should go into the PR.
=> adding IP range support to remoteAddress

CHANGELOG.md, src/strategy/remote-addresss-strategy.ts, test/strategy/remote-address-strategy.test.js, yarn.lock
Today the strategy ends up throwing, making the
whole isEnable call throw if the user has specified
an invalid IP.
It would be better to just ignore that invalid IP
and continue to check the other IPs in the list.
closes #38
=> RemoteAddressStrategy should ignore invalid IPs.

CHANGELOG.md, README.md, package.json, src/repository.ts, test/global.test.js, test/repository.test.js, test/unleash.test.js
=> Update API endoint paths for Unleash 3.x

package.json
#73 fails to do the work for npm@^4.0.0 See [here](https://docs.npmjs.com/misc/scripts#deprecation-note).
```
$ npm -v
5.6.0
$ node -v
v6.9.5
```
=> Build on prepare

.npmrc, package.json
According to [this](https://docs.npmjs.com/misc/scripts#deprecation-note) we should make sure users are using the right version of npm. If they don't use a minimum required version a build will not happen.
=> Make sure proper npm is running

src/unleash.ts
Default value for `strategies` is `[]` in the constructor so we can omit this key when we just want to use default strategies
=> Make strategies optional in UnleashConfig

README.md
While it is obvious in retrospect, I was unsure if the npm package was `unleash-client-node` or `unleash-client` when I was getting started.
=> Include install step

.gitignore, package-lock.json, package.json, src/integrations/browser-detector.ts, src/integrations/browser/browser-based-storage-utils.ts, src/integrations/browser/browser-based-timer-utils.ts, src/integrations/browser/localstorage-fs.d.ts, src/integrations/node/node-based-storage-utils.ts, src/integrations/node/node-based-timer-utils.ts, src/integrations/storage-utils.ts, src/integrations/timer-utils.ts, src/metrics.ts, src/repository.ts, src/request.ts, src/storage.ts, test/integrations/timer-utils.test.js, test/storage-browser.test.js, tsconfig.json
Add support for browsers to this client so that it can be used in both node based backend as well as front apps
Right now available solution "Unleash Client React" does not support all features of unleash and that is only useable in react apps. 
On the other hand this client can be used in any javascript application. 
1. Added [localstorage-fs](https://www.npmjs.com/package/localstorage-fs) to replicate NodeJs fs on frontend and store toggles state in browser
2. Added [bfs-path](https://www.npmjs.com/package/bfs-path) to replicate NodeJs path library
3. Replaced [request](https://www.npmjs.com/package/request) library with [axios](https://www.npmjs.com/package/axios) since axios works with both browser and node js
4. Given compatible class for "NodeJs.Timer" interface
Replace …
=> Provide Browser support - #unleash in frontend

README.md, src/metrics.ts, src/repository.ts, src/unleash.ts, test/metrics.test.js, test/repository.test.js
I'd like to propose to add a `timeout` option to unleash in order to be able to control the HTTP request timeout. The current implementation has already the timeout configurable for `get()` and `post()`. However, this is not accessible for the user.
Why?
We're using Unleash in a (relatively) time-critical path and we'd like to be able to limit the time spent on upstream requests.
=> feat: add timeout option for http requests

README.md, examples/custom_repository.js, src/client.ts, src/repository.ts, src/unleash.ts, test/unleash.test.js
Here's the PR to inject the repository. PTAL when you have time. 
What's missing from the docs:
* repository events: `data, ready, error`
* metrics events: `warn, error, registered, sent`
* storage events: `ready, persisted, error`
* client events: `warn, error`
I wasn't sure whether or not a user of this SDK should depend on the implementation details of the `repository`, `storage`, `metrics` and `client` objects. That makes changing the underlying implementation really hard. That's why i would discourage documenting that.
Though, it certainly is possible to access the internals and to subscribe to those events.
Please let me know if you want to have that documented, too. I'll add them in a separate PR.
=> feature: inject repository

CHANGELOG.md, package.json, yarn.lock
Seems like we run in to few problems after upgrading nyc from version `13.1.0` to `14.1.1`. I will investigate a bit further.
=> fix: Update nyc to version 14.1.1

README.md
metricsInterval and refreshInterval are milliseconds values, so add defaults to the docs in milliseconds as well.
=> fix: update README init param defaults to milliseconds

src/strategy/gradual-rollout-random.ts, test/strategy/gradual-rollout-random.test.js
Fix for #131 
When I set parameters for gradualRolloutRandom as `100%`，it means always enabled.
=> fix: Strategy gradualRolloutRandom random should <= 100

src/context.ts, src/unleash.ts, test/unleash.test.js
Added support for two new static context fields:
- environment
- appName
These are set in the Configuration when the client is
initialized and should be inserted in to the UnleashContext.
closes #135
=> feat: Add support for static context fields

README.md, src/metrics.ts, src/repository.ts, src/unleash.ts, test/metrics.network.test.js, test/metrics.test.js, test/repository.test.js
Resolve https://github.com/Unleash/unleash-client-node/issues/151
=> feat: customHeaderFunction to dynamic setting headers

src/repository.ts, test/unleash.test.js
Previously, if `unleash.destroy()` is called synchronously after Unleash
creation (before `process.nextTick(() => this.fetch())` is called), or while the
request `get` is in progress, polling would not actually stop.  Now we
consistently stop polling if `repository.stop()` is ever called.
Also use clearTimeout instead of clearInterval.
=> fix: ensure destroy works more consistently

src/feature.ts
We need to be able to see if a feature flag is marked "deprecated" during runtime in order to act accordingly
=> feat: Add stale property to the FeatureInterface

src/index.ts
When using `unleash-client` in a TypeScript setting it's to have public interfaces available directly instead of having to import from internals:
Before:
```ts
import type { Context } from 'unleash-client/lib/context';
import type { Variant } from 'unleash-client/lib/variant';
```
After:
```ts
import type { Context, Variant } from 'unleash-client';
```
=> feat: Expose Context and Variant interfaces

src/metrics.ts, src/repository.ts
Resolves #187. The library could not be used in Electron because Electron seems to not use `setTimeout` from Node, and therefore the `unref` method does not exist. The library seems to be working without that method when running inside a render process, so this might be a solution. Not sure about if this is a solid solution, how about it?
=> fix: Only unref timers when used in node, where unref is defined

CHANGELOG.md, package.json, src/metrics.ts, src/repository.ts, src/request.ts, test/metrics.test.js, test/repository.test.js, yarn.lock
Particular interest is the instantation of correct http(s).Agent. 
Is the two new fields and the agent function in request.ts enough so we don't instantiate a new Agent for every call we use?
fixes: #169
=> feat: Replaces request with node-fetch

src/strategy/flexible-rollout-strategy.ts, test/strategy/flexible-rollout-test.js
Stickiness on the flexible rollout strategy could be more generic.
The use case that I have:
- Our users are always part of an "organization"
- There are features that we want to rollout for all users of, let's say, 50% of organizations.
What I did:
- I added an additional stickiness type: `custom`.
- When `custom` is specified, a `contextField` must be specified as well.
- When `custom` is specified, we base stickiness based on the value of the `contextField` on the provided `context`.
- When `custom` is specified and `contextField` or it's value in the `context` is null or undefined, we return false and the flag is disabled.
=> feat: flexible rollout - custom stickiness

src/repository.ts, test/repository.test.js
Moving the customHeadersFunction evalution inside the try/catch
and ensuring we do the timedFetch inside the finally block. This
guarantees that we start a new fetch even if the customHeadersFunction
throws an error.
fixes: #179
=> fix: Keep fetching if customHeadersFunction fails.

examples/test_all_toggles.js, package.json, src/request.ts, test/request.test.js, test/unleash.network.retries.test.js, test/unleash.network.test.js, yarn.lock
In respect to some network issues discovered with node-fetch, where it does not automatically do reties for common network errors I have switched out node-fetch in favor of [make-fetch-happen](https://github.com/npm/make-fetch-happen)
I also played with the [got](https://www.npmjs.com/package/got) http client. The benefit of got is that it also support http2 and seems to be even more used in the wild. Switching to got will require us to to a larger rewrite and probably some more testing and verification.
=> feat: use make-fetch-happen instead of node-fetch

README.md, src/http-options.ts, src/metrics.ts, src/repository.ts, src/request.ts, src/unleash.ts
For #226  
Add ability to pass in an `HttpOptions` object with, as of now, only one field `rejectUnauthorized` to help with custom ca certs. The object was created if in the future other options need to be passed in such as an actual ca cert file, custom headers, proxy settings, etc.
=> Add Support for Passing an HTTP Arguments Option for rejectUnauthorized

src/unleash.ts
**Problem, for example:**
It is necessary to change the logic of the `userWithId` strategy
In `client.ts`, the search for the current strategy is done using
```
return this.strategies.find ((strategy: Strategy): boolean => strategy.name === name);
```
**Solution**
Change the order of the merge
```
const strats = strategies.concat(defaultStrategies);
```
Thus, by changing the order of merging strategies, we are able to find our changed strategy with the name `userWithId`, if we embrace it in the configuration:
```
const client = initialize({
...
strategies: [new UserWithIdStrategy()],
...
});
```
=> Changed the priority of the strategy block

README.md
This cleans up a few small language/grammar items the README
=> docs: small language/grammar cleanups to the docs

src/client.ts, src/index.ts, src/unleash.ts
Adds a forceGetVariant method which will not check the state of the parent toggle when called. This is to fix an issue in the ProxySDK, which currently resolves variant enabled state twice, which causes the % of a given variant to incorrectly resolve.
This isn't covered with unit tests, if someone can suggest a viable unit/integration test that would be great, given the statistically variant nature of the issue, it has been manually tested by manually linking the proxy sdk with the following Python script and checking visually that the distributions are within tolerance:
```
import requests
max_requests = 100
no_toggles = 0
disabled_variant = 0
var1 = 0
var2 = 0
for i in range(0, max_requests):
r = requests.get('http://localhost:3000/proxy', headers={"Authorization":"proxy-secret"}) …
```
=> Add forceGetVariant method

README.md
PR based on the issue here https://github.com/Unleash/unleash-client-node/issues/310
* Move the alternative usage section further up in the documentation as a subsection of the Initialize unleash-client section.
* Highlight in a note that when using unleash directly, that its required to add an event listener and if it is not done the application may either not start up or crash if it can't reach the unleash server.
* Remove defunct note about `require.cache`
=> Update Documentation - Clearer client alternative usage and highlight the require use of error handling

src/variant.ts
This PR changes the use of `String[]` to the use of `string[]` in the variant type definition. It is assumed that this is just done in error and doesn't actually carry any meaning.
This seems to be the only case where we're using uppercase Strings.
It's causing issues with OpenAPI typing, which says that String is not
string and that it can't compile with this issue.
=> fix: Use string[] instead of String[] for Override values

src/strategy/user-with-id-strategy.ts, test/strategy/user-with-id-strategy.test.js
Fix error when reading an empty UserWithIdStrategy in client.
```
Client.getEnabledToggles (/unleash-proxy/dist/client.js:68:14)
Array.filter (<anonymous>)
/unleash-proxy/dist/client.js:68:41
Unleash.isEnabled (/unleash-proxy/node_modules/unleash-client/lib/unleash.js:209:34)
UnleashClient.isEnabled (/unleash-proxy/node_modules/unleash-client/lib/client.js:54:21)
UnleashClient.isFeatureEnabled (/unleash-proxy/node_modules/unleash-client/lib/client.js:72:32)
Array.some (<anonymous>)
/unleash-proxy/node_modules/unleash-client/lib/client.js:78:33
UserWithIdStrategy.Strategy.isEnabledWithConstraints (/unleash-proxy/node_modules/unleash-client/lib/strategy/strategy.js:159:68)
UserWithIdStrategy.isEnabled (/unleash-proxy/node_modules/unleash-client/lib/strategy/user-with-id-strategy.js:25:45) …
```
=> fix: Cannot read property 'split' of undefined in UserWithIdStrategy

src/feature.ts
The FeatureInterface was missing the type member, despite the data containing it when using the getFeatureDefinitions function. 
I'm making a feature where an app gets all feature toggles of type experiment with a certain naming scheme. And it would be nice to use the type member without creating an extension interface in my code.
=> Type is missing from FeatureInterface

src/strategy/strategy.ts
This patches the semver constraints to resolve to false when the passed in context is not a strict semver, in order to bring this sdk up to speed with the latest version of the client specification tests
=> fix: force semver operators to resolve false against non strict semver

src/repository/index.ts, src/request.ts, src/unleash.ts
Adds the client spec header so that unleash can determine whether to inline segments or not, related to this PR: https://github.com/Unleash/unleash/pull/1640 that implements the change server side
=> feat: pass spec header so global segments can be toggled

package.json, src/strategy/strategy.ts, test/strategy/strategy-test.js, yarn.lock
We saw some inconsistent handling of missing context fields on in the SDK together with `IN` and `NOT_IN` operator. 
E.g. When the user has a `NOT_IN` and does not provide any context field the SDK should return true, while the node SDK is currently always returning false in that case.
=> fix: NOT_IN operator for missing contextField should return true.

src/strategy/strategy.ts, test/strategy/strategy-test.js
If the user passes a number instead of a string on a context field where we use the string operator the node SDK will currently crash. 
This PR adds a check that the context field is actually a string.
=> fix: string operator needs to guard against non-string values

.gitignore, src/feature.ts
Unleash is also sending project with payload, we should add it to the typings.
=> Add project to payload

src/helpers.ts, src/metrics.ts, src/unleash.ts, test/helpers.test.js
This PR adds support for `metricsJitter` which can be useful to evenly distribute the load on server for sending metrics.
This is related to https://github.com/Unleash/unleash-proxy/issues/108, and after we applied the jitter to the [python client](https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/__init__.py#L37) (which already supports this), we saw load on our server even out.
=> feat: add metrics jitter support

src/strategy/flexible-rollout-strategy.ts
It's easy to get skew when we only pick numbers between 0 and 100.
=> fix: flexible-rollout random stickiness is not random enough

README.md
This change adds a note saying that the environment config option is not the Unleash environment.
=> docs: mention that `environment` is not environment

.github/workflows/master.yaml, .github/workflows/prs.yaml, .github/workflows/release.yml
The current action is spewing out deprecation warnings.
`actions/setup-node` has had builtin `node_modules` caching for a long time at this point, so just using that seems best
(coveralls is https://github.com/coverallsapp/github-action/issues/132)
Closes #
=> chore: use builtin caching of `actions/setup-node`

package.json, tsconfig.json, yarn.lock
The current transpile target transpiles a bunch of code that's not needed, such as `async` functions and `class`es - both of which are heavily used in this code base.
You target a minimum of node 12, so that's the config I've used: https://github.com/Unleash/unleash-client-node/blob/18ee8ef5a397b8d1615dccd1bbc93edea85bfa0c/.github/workflows/master.yaml#L13
`tsconfig.json`
This is the full diff of the transpiled code: https://gist.github.com/SimenB/6608476192348cc2676dd75e6d76cdf8
=> fix: use base node12 tsconfig

src/client.ts, test/client.test.js, test/unleash.test.js
[Impression Data](https://docs.getunleash.io/reference/impression-data) is an opt-in feature. However, the previous implementation triggered events regardless of the status of the impressionData field. This fix adds a check on the status of the impressionData field on FeatureInterface before triggering the event.
src/client.ts
This fix addresses that issue however is more invasive than I would prefer. The change required making an update to the interface of the resolve variant function.
=> Fix: Add check on impressionData

src/index.ts, src/unleash.ts, test/index.test.js
`startUnleash` should wait for the `synchronized` event only when the Unleash instance isn't already synchronized.
Without the changes introduced by this PR, any subsequent invocation of `startUnleash` will produce an unresolved promise.
Closes #441
=> fix: always resolve startUnleash promise

src/index.ts, src/variant.ts
Is there any reason why we're not specifying all variant payload types and exporting them?
My use case is leveraging this in [unleash](https://github.com/unleash/unleash) so I can have proper types and type-checking.
=> fix: specify all payload types and export them

CHANGELOG.md
We use GitHub releases in current Actions
=> Deprecate CHANGELOG.md

package.json, src/client.ts, src/repository/index.ts, src/strategy/strategy.ts, src/test/client.test.ts, src/variant.ts, yarn.lock
Adding support for strategy variants.
Background: Unleash supports feature environment variants. This PR adds variants capability per strategy which is more flexible and easier to understand/implement. It makes it possible to use constraints and segments for variants.
How it's implemented?
If a strategy has a corresponding variant param it's used over the feature environment variant. 
I'm thinking if we should have env var or config param to enable this new capability in addition to variant params detection.
=> feat: strategy variants

examples/variant.js, src/strategy/strategy.ts
Interface for segments was incorrect with unnecessary fields
=> fix: remove unused segment fields

package.json, src/unleash.ts
Expose UnleashConfig type for the Unleash Proxy to use
=> feat: expose config type

package.json, src/client.ts
forceGetVariant should still be used in proxy/frontend API because it's not emitting impression events. The only difference is that it now evaluates the toggle under the hood (for the strategy variants support) because the experiments confirmed it's not skewing % distribution. I'm afraid that if we switch proxy and frontend SDK to getVariant the impression event will be emitted twice from the client SDK AND frontend API/proxy
=> fix: force get variant is back

package.json, src/client.ts, src/strategy/strategy.ts, src/variant.ts
* explicitly modelling strategy result as a discriminative union. We're discriminating on the enabled key.
* strategy variant calculation moved to the strategy instead of being spread between client and variant
* using strategy groupId for variant distribution instead of using feature name. groupId can be set to the feature name though. This change allows to set the same groupId across variants in different features strategies
=> refactor: strategy variants inside strategy

package.json, src/client.ts, src/details.json, src/feature.ts, src/test/client.test.ts, src/test/unleash.test.ts, yarn.lock
Dependent features implementation based on spec: https://github.com/Unleash/client-specification/pull/63
Extra checks that may also be covered by other SDKs (listing them since this is our reference implementation):
* metrics are not called on dependent features
* impression events are called on dependent features for easier debugging
* warning events for missing dependencies are reported once
=> feat: dependent features

src/client.ts, src/feature.ts, src/variant.ts
- Node SDK `FeatureInterface` was expecting fields not guaranteed to appear in the response from Unleash API.
- Added missing `number` variant payload type
=> Fix: match variant and feature types with Unleash OpenAPI

src/index.ts, src/unleash.ts
This PR makes the changes to `getFeatureToggleDefinitions` (ie exposing the segment data) backwards compatible by adding overload functions.
This will (appropriately) make the changes non breaking
=> fix: make exposing segment data backwards compatible

src/test/unleash.test.ts, src/unleash.ts
Prevent unleash client from starting twice. It will prevent bugs that were previously fixed in the user space: https://github.com/Unleash/unleash/pull/6141
Details:
* added boolean status similar to existing statuses not to introduce a new pattern in code
* the new started status is only used internally to prevent double repository and metrics start
=> feat: prevent double start

package.json, yarn.lock
Fix a security vulnerability reported in node-ip package. This vulnerability is not affecting us because the method at stake is not used in the SDK.
Closes #586
=> chore(security): bump node-ip dependency

README.md
In the first example that people will see, the `Authorization` header is like this 
```
customHeaders: { Authorization: 'SOME-SECRET' },
```
To me it's not super clear that API token **needs** to be passed via custom headers.
I've also standardised that value throughout the readme.
=> Making it clearer that the API token needs to be passed via custom headers

src/metrics.ts, src/repository/index.ts, src/test/metrics.test.ts, src/test/repository.test.ts
Fixes #615 by treating http 404 as a recoverable error
=> Fixes Unleash client stops fetching #615

src/helpers.ts, src/test/integration/context.test.ts
The Node SDK accepts context fields of any type and internally assumes they are strings without converting them. This means that e.g. the `IN` operator returns `false` for non-string values when we would otherwise expect it to return `true`.
Taking a strategy like `test IN 1337` as an example:
- `{ test: '1337' }` returns ✅ **TRUE** - Both are strings so they satisfy `===`
- `{ test: 1337 }` returns ❌ **FALSE** - One is a string, the other is a number, so they don't satisfy `===`
This change makes it so we convert context values to string, using `.toString()` in our context value resolver. The result is that both of these examples now return ✅ **TRUE**.
I think this is a positive change overall since it should not break any existing intended behavior and internally we're assuming the …
=> fix: handle context fields as string

src/helpers.ts, src/test/integration/context.test.ts
Follow up to https://github.com/Unleash/unleash-client-node/pull/628
I noticed we were not correctly handling falsy values in our context values due to doing a truthy check on the value when resolving it. 
By replacing that check with a more explicit `!== undefined` check we can still properly evaluate context fields such as `false` or `0`. I believe this check tracks with the original intent of simply checking whether the field is present.
Eventually all of this could be simplified to: `return context[field]?.toString() ?? context.properties?.[field]?.toString();`, but I wanted to avoid that level of refactor in this PR. I can still do it if the reviewer agrees.
Also added new tests that cover these specific cases.
=> fix: handle falsy context fields

src/helpers.ts
Follow up to https://github.com/Unleash/unleash-client-node/pull/629
Refactors `resolveContextValue` to: `return context[field]?.toString() ?? context.properties?.[field]?.toString();`, as discussed on that PR.
=> refactor: resolveContextValue

README.md, src/helpers.ts, src/unleash-config.ts, src/unleash.ts
https://linear.app/unleash/issue/2-2397/make-instance-id-autogenned-node
This makes `instanceId` an automatically generated property, instead of being set by the user.
Similar to https://github.com/Unleash/unleash-client-ruby/pull/179
Similar to https://github.com/Unleash/unleash-client-dotnet/pull/226
=> feat: automatically generated instanceId

README.md, package.json, src/request.ts, yarn.lock
Support for HTTP_PROXY and HTTPS_PROXY
E.g. If you have a proxy at http://localhost:8081 pointing to your Unleash API URL run your app that contains the Node SDK with: `HTTP_PROXY=http://localhost:8081 node my_app.js`
Design decision:
* instead of using @npmcli/agent directly that does the env var detection I decided to implement detection myself and instantiate http and https proxies directly. Those are the same proxies that the @npmcli/agent instantiates. The reason I choose to do it myself is because @npmcli/agent doesn't have any TS types and we loose autocompletion. On the other hand the low level agents have built-in TS support. 
Can be tested locally with https://github.com/kwasniew/proxy-server
=> feat: http and https proxy support

README.md, src/metrics.ts, src/repository/index.ts, src/test/metrics.test.ts
https://linear.app/unleash/issue/2-2389/extend-node-sdk-with-new-metrics
This extends the current metrics with metadata.
Tries being a bit fancy and grab other runtimes like `bun` and `deno`. E.g. if we run something in Bun that uses our SDK we can see it in the metrics payload:
Similar to: https://github.com/Unleash/unleash-client-dotnet/pull/231 and https://github.com/Unleash/unleash-client-ruby/pull/177
=> feat: extend metrics with metadata

README.md, src/helpers.ts, src/unleash-config.ts, src/unleash.ts
https://linear.app/unleash/issue/2-2427/revert-autogenned-instance-id-node
Reverts: https://github.com/Unleash/unleash-client-node/pull/637
=> chore: revert automatically generated instanceId (#637)

src/strategy/strategy.ts, src/test/strategy/strategy.test.ts
This drops the strictness check in our semver strategy constraints in favor of checking whether the semver is valid.
We found this out by trying to create a semver constraint for ourselves using the Unleash semver format (x.x.x+hash)
=> chore: drop strict check in semver in favor of checking it is valid

examples/streaming.js, examples/variant.js, package.json, src/details.json, src/repository/index.ts, src/test/repository.test.ts, src/unleash-config.ts, src/unleash.ts, yarn.lock
This is a reference implementation for the streaming client using SSE (Server-Sent Events).
The changes include:
* production code changes in the repository
* example how to test the streaming API (we test the API, not the low-level details that are tested in the ES library itself)
* example showing user facing property to enable streaming
Chosen library:
* we choose a fork of https://github.com/EventSource/eventsource at https://github.com/launchdarkly/js-eventsource
because it provides extra options such as backoff with jitter, read timeout for inactive streams. Both libraries also support HTTP headers that are not part of the SSE spec itself but useful in practice to do auth
Main logic:
* customers can specify mode (polling vs streaming) using experimentalMode property. When they opt …
=> feat: streaming poc

src/repository/index.ts, src/test/repository.test.ts, src/unleash.ts
Improving retry on streaming behavior.
Previously we were only retrying on 500 codes.
Details:
* handling unleash-connected event but we ignore it on first connect. First connect is done with a regular fetch for a safety fallback e.g. when server doesn't support streaming
* telling eventsource client to retry all types of errors so when some network proxy ends the connection without sending HTTP code we still re-connect and refetch the features from the unleash-connected event data (no data updated during proxy downtime is lost as a result)
=> fix: retry all streaming errors

src/repository/index.ts, src/test/repository.test.ts
Since edge doesn't return meta in streaming response and we don't have any use case for streaming etags I'm removing it for now. Etag may become useful when we switch between streaming and polling at runtime so that polling can know latest etag from the last streaming update.
=> fix: remove etag from streaming parsing

.github/workflows/release.yml
Updates the release template to use the new npm release v2 action, which relies on the GitHub bot instead of a personal PAT.
=> Meta: update release action to v2

.github/workflows/build-and-test.yaml, .gitignore, package.json, scripts/test-package/run.sh, scripts/test-package/test-package.json, scripts/test-package/test-tsconfig.json, src/event-source.js, src/metrics.ts, src/repository/index.ts, src/test/repository.test.ts, src/unleash.ts, tsconfig.json, yarn.lock
- fix error with dependency typings
- add test to catch install issues in the future
- update Node types, to build without errors
Closes https://github.com/Unleash/unleash-client-node/issues/705
Internal ticket: [issue/1-3339/node-sdk-missing-dependency-for-types](https://linear.app/unleash/issue/1-3339/node-sdk-missing-dependency-for-types)
=> fix: drop ts type inference for event source

src/index.ts, src/metric-client.ts
This is just a way to wrap the client in a decorator so we can limit exposure of the public API while we experiment on main. This could have been inheritance with less code, just feel this has better separation
Simple usage example moves from this:
``` node
const unleash = initialize({
appName: 'my-application',
url,
});
```
to this
``` node
const unleash = new UnleashMetricClient(initialize({
appName: 'my-application',
url,
}));
```
=> chore: add a proxy decorator to the client so we can add impact metrics unobtrusively

src/repository/index.ts
We don't need getMode in public interface for now. Impl method is enough for testing and it doesn't break Unleash usage contract for other repo impls based on the interface
=> fix: hide getMode from public repo interface

src/repository/index.ts, src/test/repository.test.ts, src/unleash.ts
Previously we added server-driven SDK mode change (https://github.com/Unleash/unleash-node-sdk/pull/758). However we can also do much simpler client/SDK driven runtime mode change.
You can set setExerimentalMode on SDK instance and it will switch automatically. This allows us to control mode per SDK client (safer internal rollout)
=> feat: sdk/client driven sdk mode change
